services:
  caddy:
    image: caddy:2.11.4
    container_name: caddy
    user: "1000:1000"
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./configs/caddy:/etc/caddy:ro
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config

  jellyfin:
    image: jellyfin/jellyfin:10.11.11
    container_name: jellyfin
    user: "1000:1000"
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/cache:/cache
      - /mnt/storage/media:/media:ro
    group_add:
      - "992" # render group
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # use system GPU
    extra_hosts:
      - "host.docker.internal:host-gateway" # necessary for docker healthcheck to pass if running in host network mode

  slskd:
    image: slskd/slskd:0.25.1
    container_name: slskd
    user: "1000:1000"
    restart: unless-stopped
    network_mode: "service:gluetun_slskd"
    environment:
      - SLSKD_SLSK_USERNAME=${SLSKD_SLSK_USERNAME}
      - SLSKD_SLSK_PASSWORD=${SLSKD_SLSK_PASSWORD}
      - SLSKD_USERNAME=${SLSKD_USERNAME}
      - SLSKD_PASSWORD=${SLSKD_PASSWORD}
      - SLSKD_SHARED_DIR=/music
      - SLSKD_DOWNLOADS_DIR=/downloads/complete
      - SLSKD_INCOMPLETE_DIR=/downloads/incomplete
      - SLSKD_VPN=true
      - SLSKD_VPN_PORT_FORWARDING=true
      - SLSKD_VPN_GLUETUN_URL=http://localhost:8000
      - SLSKD_VPN_GLUETUN_API_KEY=${GLUETUN_API_KEY}
    volumes:
      - ./data/slskd:/app
      - /mnt/storage/media/music:/music:ro
      - /mnt/storage/downloads/slskd:/downloads

  gluetun_slskd:
    image: qmcgaw/gluetun:v3.41.1
    container_name: gluetun_slskd
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "5030:5030/tcp" # Slskd WebUI
      - "5031:5031/tcp" # Slskd App
    volumes:
      - ./data/gluetun_slskd:/gluetun
    environment:
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY_SLSKD}
      SERVER_COUNTRIES: Spain
      VPN_PORT_FORWARDING: on
      HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE: '{"auth":"apikey","apikey":"${GLUETUN_API_KEY}"}'
    devices:
      - /dev/net/tun:/dev/net/tun

  homer:
    image: b4bz/homer:v26.4.2
    container_name: homer
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - INIT_ASSETS=1
    volumes:
      - ./configs/homer:/www/assets:ro

  syncthing:
    image: syncthing/syncthing:2.1.2
    container_name: syncthing
    user: "1000:1000"
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - ./data/syncthing:/var/syncthing
      - /mnt/storage/synced:/synced

  radarr:
    image: lscr.io/linuxserver/radarr:5.28.0
    container_name: radarr
    restart: unless-stopped
    network_mode: "service:gluetun_qbit" # routing via VPN to bypass ISP censorship (laliga/tebas)
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/radarr:/config
      - /mnt/storage:/data

  radarr_4k:
    image: lscr.io/linuxserver/radarr:5.28.0
    container_name: radarr_4k
    restart: unless-stopped
    network_mode: "service:gluetun_qbit" # routing via VPN to bypass ISP censorship (laliga/tebas)
    environment:
      - PUID=1000
      - PGID=1000
      - RADARR__SERVER__PORT=7879
    volumes:
      - ./data/radarr_4k:/config
      - /mnt/storage:/data

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.16
    container_name: sonarr
    restart: unless-stopped
    network_mode: "service:gluetun_qbit" # routing via VPN to bypass ISP censorship (laliga/tebas)
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/sonarr:/config
      - /mnt/storage:/data

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.2.3
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "service:gluetun_qbit"
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8081
    volumes:
      - ./data/qbittorrent:/config
      - /mnt/storage/downloads/torrents:/data/downloads/torrents

  gluetun_qbit:
    image: qmcgaw/gluetun:v3.41.1
    container_name: gluetun_qbit
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "8081:8081" # qBittorrent WebUI
      - "7878:7878" # Radarr WebUI
      - "7879:7879" # Radarr 4K WebUI
      - "8989:8989" # Sonarr WebUI
    volumes:
      - ./data/gluetun_qbit:/gluetun
    environment:
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY_QBIT}
      SERVER_COUNTRIES: Spain
      VPN_PORT_FORWARDING: on
      VPN_PORT_FORWARDING_UP_COMMAND: |
        /bin/sh -c '
          wget -O- --retry-connrefused \
          --post-data "json={\"listen_port\":{{PORTS}},\"current_network_interface\":\"tun0\",\"random_port\":false,\"upnp\":false}" \
          http://127.0.0.1:8081/api/v2/app/setPreferences 2>&1
        '
      VPN_PORT_FORWARDING_DOWN_COMMAND: |
        /bin/sh -c '
          wget -O- --retry-connrefused \
          --post-data "json={\"listen_port\":0,\"current_network_interface\":\"lo\"}" \
          http://127.0.0.1:8081/api/v2/app/setPreferences 2>&1
        '
    devices:
      - /dev/net/tun:/dev/net/tun

  audiodeck:
    image: casantosmu/audiodeck:latest
    container_name: audiodeck
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - "4747:4747"
    volumes:
      - /mnt/storage/media:/media/media:ro
      - /mnt/storage/downloads/slskd:/media/slskd:ro
