services:
  - name: "Serveis"
    icon: "fas fa-server"
    items:
      - name: "Syncthing"
        icon: "fas fa-sync-alt"
        subtitle: "Sincronització de fitxers"
        url: "http://hp-minipc:8384"
        target: "_blank"

      - name: "Jellyfin"
        icon: "fas fa-film"
        subtitle: "Servidor multimèdia"
        url: "http://hp-minipc:8096"
        target: "_blank"

      - name: "Radarr"
        icon: "fas fa-compact-disc"
        subtitle: "Gestor de pel·lícules"
        url: "http://hp-minipc:7878"
        target: "_blank"

      - name: "Radarr 4K"
        icon: "fas fa-compact-disc"
        subtitle: "Gestor de pel·lícules 4K"
        url: "http://hp-minipc:7879"
        target: "_blank"

      - name: "Sonarr"
        icon: "fas fa-tv"
        subtitle: "Gestor de sèries"
        url: "http://hp-minipc:8989"
        target: "_blank"

      - name: "qBittorrent"
        icon: "fas fa-download"
        subtitle: "Client de descàrregues"
        url: "http://hp-minipc:8081"
        target: "_blank"

      - name: "slskd"
        icon: "fas fa-music"
        subtitle: "Client de Soulseek"
        url: "http://hp-minipc:5030"
        target: "_blank"

      - name: "Audiodeck"
        icon: "fas fa-wave-square"
        subtitle: "Analitzador d'espectre d'àudio"
        url: "http://hp-minipc:4747"
        target: "_blank"
